import { registerActionContract } from "../registry";
import { quickFormatAdaptContract } from "./quick-format-adapt";
import { quickPackageContract } from "./quick-package";
import { quickPersonaSimulateContract } from "./quick-persona-simulate";
import { quickRegenerateContract } from "./quick-regenerate";
import { quickRestyleContract } from "./quick-restyle";
import { quickReviewContract } from "./quick-review";
import { quickSaveReferenceContract } from "./quick-save-reference";
import { startBrandTrainingContract } from "./start-brand-training";
import { startCompleteCampaignContract } from "./start-complete-campaign";
import { createCreativePlanContract } from "./create-creative-plan";
import { reviseCreativePlanContract } from "./revise-creative-plan";
import { reviseCreativeContract } from "./revise-creative";
import { generateCreativeTripletContract } from "./generate-creative-triplet";
import { reviseCreativeAnnotationsContract } from "./revise-creative-annotations";
import { generateGoalPackageContract } from "./generate-goal-package";

registerActionContract(quickRestyleContract);
registerActionContract(quickFormatAdaptContract);
registerActionContract(quickRegenerateContract);
registerActionContract(quickReviewContract);
registerActionContract(quickSaveReferenceContract);
registerActionContract(quickPackageContract);
registerActionContract(quickPersonaSimulateContract);
registerActionContract(startBrandTrainingContract);
registerActionContract(startCompleteCampaignContract);
registerActionContract(createCreativePlanContract);
registerActionContract(reviseCreativePlanContract);
registerActionContract(reviseCreativeContract);
registerActionContract(generateCreativeTripletContract);
registerActionContract(reviseCreativeAnnotationsContract);
registerActionContract(generateGoalPackageContract);
