import "server-only";
import { and, eq, max, sql } from "drizzle-orm";
import { db } from "@/server/db";
import { creativeWorkOutputs } from "@/server/db/schema";
import { materializeLayerEditorDraft } from "@/server/layer-editor/artifacts";
import { getCreativeWorkLayerEditorOutput, layerEditorFromOutput } from "@/server/repositories/creative-work-layer-editor";
import { objectStorage } from "@/server/storage";

export async function publishCreativeWorkLayerEditor(input:{workspaceId:string;workItemId:string;outputId:string;userId:string;leaseId:string;expectedRevision:number;operationId:string}) {
 const parent=await getCreativeWorkLayerEditorOutput(input); const state=layerEditorFromOutput(parent); if(!parent||!state||state.revision!==input.expectedRevision||state.lease?.id!==input.leaseId||state.lease.userId!==input.userId||state.regeneration)return {ok:false as const,code:"layer_editor_publish_conflict" as const};
 const draft=await materializeLayerEditorDraft({...input,revision:state.revision}); const prefix=`creative-work/${input.workItemId}/layer-editor/${input.outputId}/published/${input.operationId}`; const pngKey=`${prefix}/piece.png`,psdKey=`${prefix}/piece.psd`; await objectStorage.put(pngKey,await objectStorage.get(draft.pngKey),"image/png"); await objectStorage.put(psdKey,await objectStorage.get(draft.psdKey),"image/vnd.adobe.photoshop"); const operationKey=`layer-editor-publish:${input.operationId}`;
 return db.transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${`${input.workspaceId}:${input.workItemId}:${parent.creativeLevel}:${parent.targetFormat}`}))`); const [old]=await tx.select().from(creativeWorkOutputs).where(eq(creativeWorkOutputs.operationKey,operationKey)).limit(1); if(old)return {ok:true as const,replay:true,output:old}; const [{maxVersion}]=await tx.select({maxVersion:max(creativeWorkOutputs.versionNumber)}).from(creativeWorkOutputs).where(and(eq(creativeWorkOutputs.workItemId,input.workItemId),eq(creativeWorkOutputs.creativeLevel,parent.creativeLevel),eq(creativeWorkOutputs.targetFormat,parent.targetFormat))); const childState={...state,revision:1,lease:null,regeneration:null,publishedPsdKey:psdKey,layers:state.layers.map(l=>({...l,source:{...l.source,order:l.order,name:l.name,visible:l.visible,x:l.x,y:l.y,width:l.width,height:l.height,key:l.currentKey},currentKind:"source" as const,restorableKey:null})),updatedAt:new Date().toISOString()}; const [output]=await tx.insert(creativeWorkOutputs).values({workspaceId:input.workspaceId,workItemId:input.workItemId,creativeLevel:parent.creativeLevel,targetFormat:parent.targetFormat,versionNumber:(maxVersion??0)+1,parentOutputId:parent.id,operationKey,status:"completed",outputKey:pngKey,isSelected:false,directionId:parent.directionId,directionSnapshot:parent.directionSnapshot,layerEditor:childState,queuedAt:new Date(),terminalAt:new Date(),generationCompletedAt:new Date()}).returning(); return {ok:true as const,replay:false,output};});
}
