import type { CampaignV6Row, CampaignsV6Labels } from "@/components/campaigns/v6/campaigns-v6-types";
import { previewCampaignList } from "../_fixtures/preview-data";

export const previewCampaignsLabels: CampaignsV6Labels = {
  sectionLabel: "Trabalhos",
  versionBadge: "v1",
  title: "12 trabalhos",
  subtitle: "Campanhas e posts no mesmo lugar. Use o filtro para agrupar por tipo.",
  sortPrefix: "Ordenar",
  newCampaign: "+ Nova campanha",
  searchPlaceholder: "Buscar trabalho, peça ou cliente…",
  searchAriaLabel: "Buscar trabalho",
  filtersAria: "Filtros de trabalhos",
  statusChipPrefix: "Status",
  platformChipPrefix: "Plataforma",
  originAll: "Todos",
  originCampaigns: "Campanhas",
  originPosts: "Posts",
  viewList: "Lista",
  viewGrid: "Grade",
  viewBoard: "Quadro",
  selectCampaign: (name) => `Selecionar campanha ${name}`,
  actionsFor: (name) => `Ações para ${name}`,
  openCampaign: "Abrir",
  duplicate: "Duplicar",
  saveAsTemplate: "Salvar como template",
  archive: "Arquivar",
  delete: "Excluir",
  variationsLabel: "variações",
  approvedLabel: "aprovadas",
};

export const previewCampaignsRows: CampaignV6Row[] = previewCampaignList.map((campaign, index) => ({
  id: `preview-campaign-${index}`,
  href: "#",
  initials: campaign.initials,
  name: campaign.name,
  variations: campaign.variations,
  approved: campaign.approved,
  status: campaign.status,
  statusVariant: campaign.statusClass,
  updated: campaign.updated,
  originKind: "campaign",
  originLabel: "Campanhas",
  campaign: {
    id: `preview-campaign-${index}`,
    workspaceId: "preview",
    name: campaign.name,
    platforms: [],
    generationMode: "art_variation",
    status: "active",
    variations: campaign.variations,
    creditsUsed: 0,
    totalDerivations: campaign.variations,
    activeDerivations: 0,
    failedDerivations: 0,
    completedDerivations: campaign.approved,
    lastModified: new Date(),
    createdAt: new Date(),
  },
}));
