import type { DashboardV6ActivityRow, DashboardV6ViewModel } from "@/components/dashboard/v6/dashboard-v6-types";
import {
  previewActivity,
  previewBriefingRows,
  previewHeroMeta,
  previewKpis,
  previewRecipes,
  previewUser,
} from "../_fixtures/preview-data";

export const previewDashboardLabels = {
  greeting: `Bom dia, ${previewUser.firstName}.`,
  kpisAria: "Indicadores",
  heroProduction: "Campanha em produção",
  openCampaign: "Abrir campanha",
  viewBriefing: "Ver briefing",
  metaBriefing: "Briefing",
  metaVariations: "Variações",
  metaApproved: "Aprovadas",
  metaCredits: "Créditos",
  activityTitle: "Atividade recente",
  activitySubtitle: "Últimas campanhas e derivações aprovadas pelo time.",
  viewAll: "Ver todas →",
  tableCampaign: "Campanha",
  tableStatus: "Status",
  tablePlatform: "Plataforma",
  tableVariations: "Variações",
  tableUpdated: "Atualizada",
  recipesTitle: "Receitas salvas",
  recipesSubtitle: "Briefings que viraram template. Reaproveite a próxima campanha com 1 clique.",
  briefingTitle: "Briefing ativo",
  editBriefing: "Editar",
  goToActions: "Ir para ações",
  activityEmptyTitle: "Nenhuma atividade recente",
  activityEmptyDescription: "Campanhas e derivações em que você trabalhar aparecerão aqui.",
  activityEmptyAction: "Criar campanha",
  recipesEmptyTitle: "Nenhuma receita salva ainda",
  recipesEmptyDescription: "Salve um briefing como template para reutilizar na próxima campanha.",
  recipesEmptyAction: "Ver templates",
  briefingEmptyTitle: "Nenhum briefing ativo",
  briefingEmptyDescription: "Inicie um briefing de campanha ou escolha um template para ver os campos aqui.",
  briefingEmptyAction: "Nova campanha",
};

export const previewDashboardView: DashboardV6ViewModel = {
  firstName: previewUser.firstName,
  inReviewCount: 3,
  readyToApproveCount: 2,
  kpis: previewKpis.map((kpi) => ({
    label: kpi.label,
    value: kpi.value,
    trend: kpi.trend,
    trendDir: kpi.trendDir,
  })),
  hero: {
    id: "preview-hero",
    name: "Verão 2024 — Natura",
    badge: "Piloto",
    badgeClass: "warning",
    description: "Briefing concluído · gerando 24 variações em 3 tamanhos · última execução em 47s.",
    briefingProgress: previewHeroMeta.briefingProgress,
    variationsDone: previewHeroMeta.variationsDone,
    variationsTotal: previewHeroMeta.variationsTotal,
    approved: previewHeroMeta.approved,
    credits: previewHeroMeta.credits,
  },
  activity: previewActivity.map((row, index) => ({
    id: `preview-activity-${index}`,
    href: "#",
    thumb: row.thumb,
    name: row.name,
    subtitle: `${row.author} · ${row.updated}`,
    status: row.status,
    statusClass: row.statusClass as DashboardV6ActivityRow["statusClass"],
    platforms: row.platforms,
    variations: row.variations,
    updated: row.updated,
  })),
  recipes: previewRecipes.map((recipe, index) => ({
    id: `preview-recipe-${index}`,
    icon: recipe.icon,
    name: recipe.name,
    desc: recipe.desc,
    count: recipe.count,
    href: "#",
  })),
  briefingRows: previewBriefingRows,
  activeBriefingCampaignId: "preview-hero",
};
