import type { Actor } from "../domain";
import { executeCommand } from "../module/commands";
import { handoffText } from "@/lib/equipe/handoff-copy";
// Equipe chat turn (#551): the adapter between the assistant chat route and
// the #550 strategist.
//
// The turn writes through an injected conversation writer (live: the
// assistant message repository) and thinks through the #550 Agents port —
// so the monthly budget cap and the cost ledger apply to chat turns exactly
// like job turns. Approval intent in text ("ok, pode postar") short-circuits
// before any model call: the turn answers with the `equipe_card` of the
// pending batch/item. That path never calls the model and never runs a
// command — the chat cannot approve anything.

import type { EquipeCardPayload } from "@/server/repositories/assistant-types";
import { createAssistantMessage, createAssistantPlanOfferOnce, listAssistantMessages, type CreateAssistantMessageInput, type UserMessageAttachment } from "@/server/repositories/assistant-message";
import { detectApprovalIntent, normalizeIntentText } from "@/lib/equipe/approval-intent";
import { filterSuggestions } from "@/lib/equipe/suggestions";
import { DIAGNOSIS_CORRECT_SOURCE_PHRASE, DIAGNOSIS_RETRY_PHRASE, isDiagnosisPhrase } from "@/lib/equipe/diagnosis-copy";
import type { Agents, EquipeModuleDeps } from "../module/ports";
import { resolvePendingCard } from "./cards";
import { BUDGET_EXCEEDED_ERROR } from "./runner";
import { authorizeAccountExecution, isExecutionBlocked } from "../module/execution-authorization";
import { hasRecordedDiagnostic } from "./free-budget";
import { isReadingStuck } from "../handoff/diagnosis-state";

export type ConversationPostInput = CreateAssistantMessageInput;

/** Message sink for turns and proactive posts. Live: assistant repository. */
export type EquipeConversationWriter = {
  post(input: ConversationPostInput): Promise<{ id: string }>;
  list(threadId: string, options: { limit: number }): Promise<Array<{ type: string; content: string; payload?: unknown }>>;
  /**
   * Posts a plan offer unless the thread already carries one, atomically: turns
   * racing on the thread (two tabs) cannot both offer. `created: false` means
   * another offer came first. A writer without it posts unconditionally.
   */
  postPlanOfferOnce?(input: ConversationPostInput): Promise<{ id: string; created: boolean }>;
};

export function liveConversationWriter(workspaceId: string): EquipeConversationWriter {
  return {
    list: (threadId, options) => listAssistantMessages(workspaceId, threadId, options),
    async post(input) {
      const row = await createAssistantMessage(workspaceId, input);
      return { id: row.id };
    },
    async postPlanOfferOnce(input) {
      const { row, created } = await createAssistantPlanOfferOnce(workspaceId, input);
      return { id: row.id, created };
    },
  };
}

export type EquipeChatTurnEvent =
  | { type: "text_delta"; text: string }
  | { type: "equipe_card"; messageId: string; card: EquipeCardPayload }
  | { type: "done"; assistantMessageId: string }
  | { type: "error"; message: string };

export type EquipeChatTurnInput = {
  deps: EquipeModuleDeps;
  agents: Agents;
  messages: EquipeConversationWriter;
  workspaceId: string;
  accountId: string;
  /** Assistant thread id (the map entry's `assistantThreadId`). */
  threadId: string;
  userMessage: string;
  actor?: Actor;
  locale?: string;
  fromSuggestion?: boolean;
  /**
   * Validated attachments (the route checked workspace, key and type). They are
   * kept in the person's message for the history and for staff; the strategist
   * never receives them, and the free account refuses to analyze them.
   */
  attachments?: UserMessageAttachment[];
  /** Localized service notice; deterministic, never generated by the model. */
  executionPausedMessage: string;
  maxIterations?: number;
};

// The detector is shared with the suggestion filter (src/lib/equipe); chat-turn keeps exporting it.
export { detectApprovalIntent };

const PLAN_REQUEST_PATTERNS = [
  /\b(?:quero|queria|gostaria de|vamos|bora)\s+(?:\w+\s+){0,2}?(?:assinar|contratar)\b/,
  /\bcomo\s+(?:faco|fazer)\s+(?:pra|para)\s+(?:assinar|contratar)\b/,
  /\bcomo\s+(?:assino|contrato)\b/,
  /\b(?:quero|queria|gostaria de)\s+(?:\w+\s+){0,3}?(?:o|um)\s+plano\b(?!\s+(?:gratis|gratuito))/,
  /\bassinar\s+o\s+plano\b/,
];

// Statements are judged one by one: punctuation, dashes, line breaks and the conjunctions that open a new one.
const CLAUSE_BREAKS = /[;,.!?:\n–—-]|\s+(?:e|mas|porém|porem|contudo|todavia|entretanto|pois|porque)\s+/;

/**
 * Conservative "I want the plan" detector (pt-BR) — the only thing that brings
 * the plan card back once the free conversation is over. A negation vetoes
 * only the clause it is in ("não quero assinar"), so "não quero continuar no
 * grátis; quero assinar o plano" still asks for the plan. When in doubt the
 * person gets the fixed reply, which tells them how to ask.
 */
export function detectPlanRequest(text: string): boolean {
  return text.toLowerCase().split(CLAUSE_BREAKS).some((clause) => {
    const normalized = normalizeIntentText(clause);
    return !/\b(?:nao|nem|nunca|jamais)\b/.test(normalized)
      && PLAN_REQUEST_PATTERNS.some((pattern) => pattern.test(normalized));
  });
}

/** Marks the plan offer posted because the free AI budget ran out. */
const FREE_BUDGET_EXHAUSTED_OFFER = "free_budget_exhausted" as const;

/**
 * Answer to every message after that offer. A constant on purpose: the next
 * turn recognizes it in the thread, and it is never generated by the model.
 */
const FREE_BUDGET_EXHAUSTED_REPLY =
  "Sua conversa grátis com a IA chegou ao limite. O diagnóstico e a Biblioteca continuam disponíveis; para conhecer o plano, é só dizer “quero assinar”.";

function cardMessageContent(card: EquipeCardPayload): string {
  if (card.kind === "batch") {
    return `${card.title} — ${card.items.length} pronto(s) para revisar`;
  }
  return `Para revisar: ${card.title}`;
}

async function* pausedTurn(input: EquipeChatTurnInput): AsyncGenerator<EquipeChatTurnEvent> {
  const posted = await input.messages.post({
    threadId: input.threadId, type: "assistant", content: input.executionPausedMessage,
  });
  yield { type: "text_delta", text: input.executionPausedMessage };
  yield { type: "done", assistantMessageId: posted.id };
}

async function* runApprovalIntentTurn(
  input: EquipeChatTurnInput,
): AsyncGenerator<EquipeChatTurnEvent> {
  const card = await resolvePendingCard(input.deps.uow.repos, input.workspaceId, input.accountId);
  if (!(await authorizeAccountExecution(input.deps.uow.repos, input)).ok) {
    yield* pausedTurn(input);
    return;
  }
  if (!card) {
    const content = "Não há nada aguardando sua aprovação agora. Quando um lote ficar pronto, eu aviso aqui.";
    const posted = await input.messages.post({
      threadId: input.threadId,
      type: "assistant",
      content,
    });
    yield { type: "text_delta", text: content };
    yield { type: "done", assistantMessageId: posted.id };
    return;
  }
  const content = cardMessageContent(card);
  const posted = await input.messages.post({
    threadId: input.threadId,
    type: "equipe_card",
    content,
    payload: { ...card, items: card.items.map((item) => ({ ...item })) },
  });
  yield { type: "equipe_card", messageId: posted.id, card };
  yield { type: "done", assistantMessageId: posted.id };
}

async function* planOfferTurn(
  input: EquipeChatTurnInput,
  reason?: typeof FREE_BUDGET_EXHAUSTED_OFFER,
  once = false,
): AsyncGenerator<EquipeChatTurnEvent> {
  const card: EquipeCardPayload = {
    kind: "plan_offer", accountId: input.accountId, title: "ADScale para a sua marca", items: [], ...(reason ? { reason } : {}),
  };
  const message = { threadId: input.threadId, type: "equipe_card" as const, content: card.title, payload: { ...card } };
  const posted = once && input.messages.postPlanOfferOnce
    ? await input.messages.postPlanOfferOnce(message)
    : { ...(await input.messages.post(message)), created: true };
  if (!posted.created) {
    // Another turn offered first; this one is answered like every later message.
    yield* freeBudgetExhaustedReply(input);
    return;
  }
  yield { type: "equipe_card", messageId: posted.id, card };
  yield { type: "done", assistantMessageId: posted.id };
}

async function* freeBudgetExhaustedReply(input: EquipeChatTurnInput): AsyncGenerator<EquipeChatTurnEvent> {
  const posted = await input.messages.post({ threadId: input.threadId, type: "assistant", content: FREE_BUDGET_EXHAUSTED_REPLY });
  yield { type: "text_delta", text: FREE_BUDGET_EXHAUSTED_REPLY };
  yield { type: "done", assistantMessageId: posted.id };
}

/**
 * The free budget is gone and the diagnosis is done. The offer is made once —
 * or again when the person asks for the plan — and every other message gets
 * the same fixed reply. Otherwise "Agora não" would send a message that
 * recreates the card it just dismissed. The first offer is posted only if the
 * thread still has none, checked atomically: two tabs refused at the same
 * moment, or an offer older than the history window, never bring a second one.
 */
async function* freeBudgetExhaustedTurn(input: EquipeChatTurnInput, offered: boolean): AsyncGenerator<EquipeChatTurnEvent> {
  const requested = detectPlanRequest(input.userMessage);
  if (offered && !requested) {
    yield* freeBudgetExhaustedReply(input);
    return;
  }
  yield* planOfferTurn(input, FREE_BUDGET_EXHAUSTED_OFFER, !requested);
}

type ThreadMessage = { type: string; content: string; payload?: unknown };

function payloadOf(message: ThreadMessage): Record<string, unknown> {
  return message.payload && typeof message.payload === "object" ? message.payload as Record<string, unknown> : {};
}

function isPlanOfferCard(message: ThreadMessage) {
  return message.type === "equipe_card" && payloadOf(message).kind === "plan_offer";
}

/** The last conversational reply: neither the person's own messages nor the feed lines ("Recebemos seu pedido…") count. */
function lastReply(messages: ThreadMessage[]) {
  return [...messages].reverse().find((message) => message.type !== "user" && message.type !== "equipe_event");
}

/** The last thing the person was told is that the free conversation is over. */
function closesFreeConversation(message: ThreadMessage | undefined) {
  if (!message) return false;
  return message.type === "assistant"
    ? message.content === FREE_BUDGET_EXHAUSTED_REPLY
    : isPlanOfferCard(message) && payloadOf(message).reason === FREE_BUDGET_EXHAUSTED_OFFER;
}

/** Only visible text enters the model: payloads may contain private refs or attachments. */
function historyMessage(message: ThreadMessage) {
  const payload = payloadOf(message);
  const content = message.type === "equipe_card" || message.type === "action_card"
    ? `[card: ${String(payload.kind ?? message.type)} · ${message.content}${Array.isArray(payload.opportunities) ? ` · ${payload.opportunities.length} oportunidades` : ""}]`
    : message.content;
  return { role: message.type === "user" ? "user" as const : "assistant" as const,
    content: (message.type.endsWith("card") ? content.replace(/\s+/g, " ") : content).slice(0, 2000) };
}

export async function* runEquipeStrategistTurn(
  input: EquipeChatTurnInput,
): AsyncGenerator<EquipeChatTurnEvent> {
  const allowed = await authorizeAccountExecution(input.deps.uow.repos, input);
  const recent = allowed.ok ? (await input.messages.list(input.threadId, { limit: 20 })).slice(-20) : [];
  const history = recent.map(historyMessage);
  const attachments = input.attachments ?? [];
  const payload = {
    ...(attachments.length ? { attachments } : {}),
    ...(input.fromSuggestion ? { fromSuggestion: true } : {}),
  };
  await input.messages.post({
    threadId: input.threadId,
    type: "user",
    // Never blank: an image-only message says so (without the file name, which is not for the model).
    content: input.userMessage || (attachments.length ? (attachments.length === 1 ? "Imagem anexada" : "Imagens anexadas") : ""),
    ...(Object.keys(payload).length ? { payload } : {}),
  });

  // Keep the client's message for human follow-up, but do not retrieve cards,
  // account context or invoke the strategist while execution is suspended.
  if (!(await authorizeAccountExecution(input.deps.uow.repos, input)).ok) {
    yield* pausedTurn(input);
    return;
  }

  let [handoff] = await input.deps.uow.repos.handoffs.list(input);
  if (handoff && handoff.step !== "done") {
    let text = handoffText(handoff.step === "source" ? "source" : "pending", input.locale);
    const source = input.userMessage.match(/https?:\/\/[^\s<>]+|@[a-zA-Z0-9_.]+/i)?.[0];
    if (handoff.step === "source" && source && input.actor) {
      const outcome = await executeCommand(input.deps, { workspaceId: input.workspaceId, accountId: input.accountId, actor: input.actor }, {
        type: "handoff_set_source", payload: { expectedStep: handoff.step, expectedVersion: handoff.version, kind: source.startsWith("@") || /instagram\.com\//i.test(source) ? "instagram" : "site", value: source },
      });
      [handoff] = await input.deps.uow.repos.handoffs.list(input);
      if (outcome.ok && handoff) {
        const card: EquipeCardPayload = { kind: "handoff", accountId: input.accountId, handoffId: handoff.id, step: handoff.step, title: handoffText(handoff.step, input.locale), items: [] };
        const event = outcome.value.events.find(e => e.eventType === "handoff.card")!;
        yield { type: "equipe_card", messageId: event.id, card };
        yield { type: "done", assistantMessageId: event.id };
        return;
      }
      text = handoffText(!outcome.ok && outcome.error.code === "reading_limit" ? "limit" : "invalid", input.locale);
    }
    // All readings used and the brand cannot move on: a free account that already has a recorded diagnosis (a correction
    // that ran out of readings) is told so and gets the plan card, still without a model call. The card is offered once
    // (or again when the person asks for the plan): "Agora não" sends a message that must not recreate the card it dismissed.
    const stuckWithDiagnosis = Boolean(handoff && isReadingStuck(handoff))
      && (await input.deps.uow.repos.accounts.get(input.workspaceId, input.accountId))?.status === "free"
      && await hasRecordedDiagnostic(input.deps.uow.repos, input);
    if (stuckWithDiagnosis) text = handoffText("limit", input.locale);
    const offerPlan = stuckWithDiagnosis && (!recent.some(isPlanOfferCard) || detectPlanRequest(input.userMessage));
    const posted = await input.messages.post({ threadId: input.threadId, type: "assistant", content: text });
    yield { type: "text_delta", text };
    if (handoff) {
      const card: EquipeCardPayload = { kind: "handoff", accountId: input.accountId, handoffId: handoff.id, step: handoff.step, title: handoffText(handoff.step, input.locale), items: [] };
      const postedCard = await input.messages.post({ threadId: input.threadId, type: "equipe_card", content: card.title, payload: { ...card } });
      yield { type: "equipe_card", messageId: postedCard.id, card };
    }
    if (offerPlan) {
      yield* planOfferTurn(input);
      return;
    }
    yield { type: "done", assistantMessageId: posted.id };
    return;
  }

  // Once the exhaustion offer (or the fixed reply after it) is the last thing
  // said, the strategist and its budget gate stay out: the gate's verdict
  // depends on the size of each request, so a shorter message could slip
  // through and break the stable reply. This comes before every branch that
  // would answer with another reply (attachment refusal, approval): that reply
  // would become the last one and reopen the conversation.
  if (closesFreeConversation(lastReply(recent))
    && (await input.deps.uow.repos.accounts.get(input.workspaceId, input.accountId))?.status === "free") {
    yield* freeBudgetExhaustedTurn(input, true);
    return;
  }

  if (attachments.length > 0 && (await input.deps.uow.repos.accounts.get(input.workspaceId, input.accountId))?.status === "free") {
    const content = "Na conta grátis, ainda não consigo analisar imagens anexadas. Envie sua mensagem em texto ou use a leitura do site para receber o diagnóstico.";
    const posted = await input.messages.post({ threadId: input.threadId, type: "assistant", content });
    yield { type: "text_delta", text: content };
    yield { type: "done", assistantMessageId: posted.id };
    return;
  }

  // The diagnosis cards' iscas come back as messages: the server answers them itself, without a model call.
  const retry = isDiagnosisPhrase(input.userMessage, DIAGNOSIS_RETRY_PHRASE);
  if (input.actor && handoff?.step === "done" && (retry || isDiagnosisPhrase(input.userMessage, DIAGNOSIS_CORRECT_SOURCE_PHRASE))) {
    const outcome = await executeCommand(input.deps, { workspaceId: input.workspaceId, accountId: input.accountId, actor: input.actor }, {
      type: retry ? "diagnosis_retry" : "diagnosis_correct_source", payload: {},
    });
    const cardEvent = outcome.ok ? outcome.value.events.find(e => e.eventType === "handoff.card") : undefined;
    if (cardEvent) {
      // The command already posted the source-step card; hand it to the stream like the handoff turn does.
      const [reopened] = await input.deps.uow.repos.handoffs.list(input);
      if (reopened) {
        const card: EquipeCardPayload = { kind: "handoff", accountId: input.accountId, handoffId: reopened.id, step: reopened.step, title: handoffText(reopened.step, input.locale), items: [] };
        yield { type: "equipe_card", messageId: cardEvent.id, card };
        yield { type: "done", assistantMessageId: cardEvent.id };
        return;
      }
    }
    // Always a fixed answer: an old card's isca clicked twice must not spend a model call.
    const code = outcome.ok ? "ok" : outcome.error.code;
    if (code === "insufficient_balance") {
      // The cap cannot cover one more reading plus the diagnosis: say so plainly, then the plan card (the diagnosis is recorded).
      const content = "Seu saldo grátis de IA não cobre uma nova leitura e um novo diagnóstico. Sua conta e sua Biblioteca continuam disponíveis.";
      const posted = await input.messages.post({ threadId: input.threadId, type: "assistant", content });
      yield { type: "text_delta", text: content };
      if (await hasRecordedDiagnostic(input.deps.uow.repos, input)) {
        yield* planOfferTurn(input);
        return;
      }
      yield { type: "done", assistantMessageId: posted.id };
      return;
    }
    const content = code === "ok" ? "Vou montar o diagnóstico de novo. Aviso quando estiver pronto."
      : code === "diagnosis_retry_limit" || code === "reading_limit" ? "Não consigo tentar de novo por aqui. Sua conta e sua Biblioteca continuam disponíveis."
        : retry ? "O diagnóstico não está com falha agora, então não há o que tentar de novo."
          : "A fonte só pode ser corrigida quando o diagnóstico pede mais conteúdo.";
    // A retry in flight keeps the conversation polling until the new diagnosis card arrives.
    const posted = await input.messages.post({ threadId: input.threadId, type: "assistant", content, ...(code === "ok" && retry ? { payload: { diagnosis: "pending" } } : {}) });
    yield { type: "text_delta", text: content };
    yield { type: "done", assistantMessageId: posted.id };
    return;
  }

  // A suggestion click is a conversation starter, never a decision: approval comes
  // from typed text or from the card, whatever the suggestion says.
  if (!input.fromSuggestion && detectApprovalIntent(input.userMessage)) {
    yield* runApprovalIntentTurn(input);
    return;
  }

  const result = await input.agents.runTask({
    kind: "strategist_turn",
    workspaceId: input.workspaceId,
    accountId: input.accountId,
    input: {
      message: input.userMessage,
      history,
      ...(input.maxIterations !== undefined ? { maxIterations: input.maxIterations } : {}),
    },
  });

  if (isExecutionBlocked(result.error) || !(await authorizeAccountExecution(input.deps.uow.repos, input)).ok) {
    yield* pausedTurn(input);
    return;
  }

  if (!result.ok) {
    const account = await input.deps.uow.repos.accounts.get(input.workspaceId, input.accountId);
    const free = account?.status === "free";
    if (free && result.error === BUDGET_EXCEEDED_ERROR && await hasRecordedDiagnostic(input.deps.uow.repos, input)) {
      yield* freeBudgetExhaustedTurn(input, recent.some(isPlanOfferCard));
      return;
    }
    const content =
      result.error === BUDGET_EXCEEDED_ERROR
        ? free ? "Não consigo continuar a conversa grátis agora. Sua conta e sua Biblioteca continuam disponíveis; conclua ou retome a leitura para receber o diagnóstico."
          : "Passei do limite de IA deste mês, então não consigo responder agora. O ADScale já foi avisado."
        : "Não consegui processar sua mensagem agora. Tente de novo em instantes.";
    const posted = await input.messages.post({
      threadId: input.threadId,
      type: "assistant",
      content,
    });
    yield { type: "text_delta", text: content };
    yield { type: "done", assistantMessageId: posted.id };
    return;
  }

  const output = result.output as { text?: string | null; suggestions?: unknown; planOffered?: boolean } | undefined;
  if (output?.planOffered) {
    const account = await input.deps.uow.repos.accounts.get(input.workspaceId, input.accountId);
    if (account?.status === "free" && await hasRecordedDiagnostic(input.deps.uow.repos, input)) {
      yield* planOfferTurn(input);
      return;
    }
  }
  const content =
    output?.text?.trim() ||
    "Atualizei a conta, mas não consegui escrever o resumo. Pergunte de novo que eu detalho.";
  const posted = await input.messages.post({
    threadId: input.threadId,
    type: "assistant",
    content,
    payload: { suggestions: filterSuggestions(output?.suggestions) },
  });
  yield { type: "text_delta", text: content };
  yield { type: "done", assistantMessageId: posted.id };
}
