// Two replies the real Opus wrote (ticket 15, free conversation, fictional brand): the answer in pt-BR, then the call spelled out as TEXT, with
// `stop_reason: tool_use` and no `tool_use` block. Captured verbatim from the real-provider test; nothing in them is personal data.

export const REAL_LEAKED_FIRST = {
  text: "Nas fontes lidas para o diagnóstico (o site e o Instagram), **não encontrei estas 4 informações:**\n\n1. **Público-alvo definido**: o site fala em \"equipes de marketing que querem crescer com dados\" e o Instagram fala em \"quem decide\". Mesmo assim, não achei uma definição clara de quem é o seu público, como cargo, porte da empresa ou setor.\n2. **Preço dos anúncios**: não há nenhum valor publicado sobre anúncios.\n3. **Resultados de campanhas anteriores**: não achei números, como assinantes da newsletter, alcance ou conversões.\n4. **Calendário de publicações**: não identifiquei com que frequência ou em que dias você publica, a não ser a indicação de que a newsletter é semanal.\n\n**O que isso muda:** não preencho essas lacunas por conta própria. Sem esses dados, não dá para dizer, por exemplo, quanto cada oportunidade traria de resultado. Se você tiver essas informações, me conte aqui e eu as levo em conta na nossa conversa sobre a marca.\n\n<invoke name=\"sugerir_proximos_passos\">\n<parameter name=\"resposta\">Nas fontes lidas para o diagnóstico (o site e o Instagram), **não encontrei estas 4 informações:**\n\n1. **Público-alvo definido**: o site fala em \"equipes de marketing que querem crescer com dados\" e o Instagram fala em \"quem decide\". Mesmo assim, não achei uma definição clara de quem é o seu público, como cargo, porte da empresa ou setor.\n2. **Preço dos anúncios**: não há nenhum valor publicado sobre anúncios.\n3. **Resultados de campanhas anteriores**: não achei números, como assinantes da newsletter, alcance ou conversões.\n4. **Calendário de publicações**: não identifiquei com que frequência ou em que dias você publica, a não ser a indicação de que a newsletter é semanal.\n\n**O que isso muda:** não preencho essas lacunas por conta própria. Sem esses dados, não dá para dizer, por exemplo, quanto cada oportunidade traria de resultado. Se você tiver essas informações, me conte aqui e eu as levo em conta na nossa conversa sobre a marca.</parameter>\n<parameter name=\"itens\">[\"Quero contar quem é meu público-alvo\", \"Me explica a oportunidade 2\", \"Por que o LinkedIn e o YouTube não aparecem?\"]</parameter>\n</invoke>",
  answer: "Nas fontes lidas para o diagnóstico (o site e o Instagram), **não encontrei estas 4 informações:**\n\n1. **Público-alvo definido**: o site fala em \"equipes de marketing que querem crescer com dados\" e o Instagram fala em \"quem decide\". Mesmo assim, não achei uma definição clara de quem é o seu público, como cargo, porte da empresa ou setor.\n2. **Preço dos anúncios**: não há nenhum valor publicado sobre anúncios.\n3. **Resultados de campanhas anteriores**: não achei números, como assinantes da newsletter, alcance ou conversões.\n4. **Calendário de publicações**: não identifiquei com que frequência ou em que dias você publica, a não ser a indicação de que a newsletter é semanal.\n\n**O que isso muda:** não preencho essas lacunas por conta própria. Sem esses dados, não dá para dizer, por exemplo, quanto cada oportunidade traria de resultado. Se você tiver essas informações, me conte aqui e eu as levo em conta na nossa conversa sobre a marca.",
  itens: ["Quero contar quem é meu público-alvo", "Me explica a oportunidade 2", "Por que o LinkedIn e o YouTube não aparecem?"],
};

export const REAL_LEAKED_SECOND = {
  text: "Encontrei e confirmei **3 redes sociais** da Conteúdo Martech:\n\n1. **Instagram**: @conteudomartech\n2. **LinkedIn**: página da empresa (linkedin.com/company/conteudomartech)\n3. **YouTube**: @conteudomartech\n\n**O que entrou no diagnóstico:** a análise de canais e as 3 oportunidades usam só o **site** e o **Instagram**. Do Instagram, encontrei posts que resumem os guias e chamam para a newsletter e para o link da bio.\n\n**O que fica em aberto:** o LinkedIn e o YouTube estão confirmados na conta, mas o diagnóstico não traz o que vocês publicam neles. Por isso não posso dizer como esses canais se encaixam nas oportunidades. Se quiser, me conte como vocês usam cada um e seguimos a conversa sobre a marca com essa informação.\n\n<invoke name=\"sugerir_proximos_passos\">\n<parameter name=\"resposta\">Encontrei e confirmei **3 redes sociais** da Conteúdo Martech:\n\n1. **Instagram**: @conteudomartech\n2. **LinkedIn**: página da empresa (linkedin.com/company/conteudomartech)\n3. **YouTube**: @conteudomartech\n\n**O que entrou no diagnóstico:** a análise de canais e as 3 oportunidades usam só o **site** e o **Instagram**. Do Instagram, encontrei posts que resumem os guias e chamam para a newsletter e para o link da bio.\n\n**O que fica em aberto:** o LinkedIn e o YouTube estão confirmados na conta, mas o diagnóstico não traz o que vocês publicam neles. Por isso não posso dizer como esses canais se encaixam nas oportunidades. Se quiser, me conte como vocês usam cada um e seguimos a conversa sobre a marca com essa informação.</parameter>\n<parameter name=\"itens\">[\"Como usamos o LinkedIn hoje\", \"Me explica a oportunidade 2\", \"Qual identidade visual vocês acharam?\"]</parameter>\n</invoke>",
  answer: "Encontrei e confirmei **3 redes sociais** da Conteúdo Martech:\n\n1. **Instagram**: @conteudomartech\n2. **LinkedIn**: página da empresa (linkedin.com/company/conteudomartech)\n3. **YouTube**: @conteudomartech\n\n**O que entrou no diagnóstico:** a análise de canais e as 3 oportunidades usam só o **site** e o **Instagram**. Do Instagram, encontrei posts que resumem os guias e chamam para a newsletter e para o link da bio.\n\n**O que fica em aberto:** o LinkedIn e o YouTube estão confirmados na conta, mas o diagnóstico não traz o que vocês publicam neles. Por isso não posso dizer como esses canais se encaixam nas oportunidades. Se quiser, me conte como vocês usam cada um e seguimos a conversa sobre a marca com essa informação.",
  itens: ["Como usamos o LinkedIn hoje", "Me explica a oportunidade 2", "Qual identidade visual vocês acharam?"],
};
