import { act, renderHook } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
const patch=vi.hoisted(()=>vi.fn());
vi.mock("@/lib/hooks/use-creative-work",()=>({patchCreativeWork:(...args:unknown[])=>patch(...args)}));
import { useLayerEditor } from "./useLayerEditor";
const document:any={schemaVersion:1,revision:1,canvas:{width:100,height:100},lease:{mode:"edit",leaseId:"00000000-0000-4000-8000-000000000001",heldByName:null,expiresAt:null},regeneration:null,updatedAt:"2026-01-01T00:00:00.000Z",layers:[0,1].map(n=>({id:`00000000-0000-4000-8000-00000000000${n+1}`,order:n,name:"Layer",visible:true,x:0,y:0,width:10,height:10,currentKind:"source",imageUrl:"x",source:{order:n,name:"Layer",visible:true,x:0,y:0,width:10,height:10,imageUrl:"x"}}))};
describe("useLayerEditor",()=>{
 it("debounces save until 750ms",async()=>{vi.useFakeTimers();patch.mockImplementation(async (_work:string,body:any)=>({document:body.action==="saveLayerEditor"?{...document,revision:2}:document}));const h=renderHook(()=>useLayerEditor({workItemId:"w",outputId:"o",mode:"edit"}));await act(async()=>{await Promise.resolve()});expect(patch).toHaveBeenCalledTimes(1);act(()=>h.result.current.dispatch({type:"rename",id:document.layers[0].id,name:"Next"}));await act(async()=>{await vi.advanceTimersByTimeAsync(749)});expect(patch).toHaveBeenCalledTimes(1);await act(async()=>{await vi.advanceTimersByTimeAsync(1)});expect(patch).toHaveBeenCalledTimes(2);vi.useRealTimers()});
 it("keeps a local history for undo and redo",async()=>{patch.mockResolvedValue({document});const h=renderHook(()=>useLayerEditor({workItemId:"w",outputId:"o",mode:"edit"}));await act(async()=>{await Promise.resolve()});act(()=>h.result.current.dispatch({type:"rename",id:document.layers[0].id,name:"Renomeada"}));expect(h.result.current.canUndo).toBe(true);act(()=>h.result.current.undo());expect(h.result.current.document?.layers[0].name).toBe("Layer");expect(h.result.current.canRedo).toBe(true);act(()=>h.result.current.redo());expect(h.result.current.document?.layers[0].name).toBe("Renomeada")});
});
